apiVersion: v1
kind: Namespace
metadata:
  name: sveltekit-k8s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sveltekit-k8s-deployment
  namespace: sveltekit-k8s
  labels:
    app: sveltekit-k8s
spec:
  replicas: 6
  selector:
    matchLabels:
      app: sveltekit-k8s
  template:
    metadata:
      labels:
        app: sveltekit-k8s
    spec:
      containers:
        - name: sveltekit-k8s
          image: aerofractal/sveltekit-k8s
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: sveltekit-k8s-svc
  namespace: sveltekit-k8s
spec:
  selector:
    app: sveltekit-k8s
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sveltekit-k8s-certificate
  namespace: sveltekit-k8s
spec:
  secretName: sveltekit-k8s-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - svelte.lab.rdmusic.net
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sveltekit-k8s-ingress
  namespace: sveltekit-k8s
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`svelte.lab.rdmusic.net`)
      kind: Rule
      services:
        - name: sveltekit-k8s-svc
          port: 80
  tls:
    secretName: sveltekit-k8s-secret
